/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import home.home;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import Model.Model_Login;
//import java.sql.Blob;

public class login extends javax.swing.JFrame {
    
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        logbtn.setEnabled(true);
    }

    public void clear(){
        emailAdd.setText("");
        pword.setText("");
        logbtn.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new PanelRound.PanelRound();
        regbtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logbtn = new javax.swing.JButton();
        pword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        emailAdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1194, 834));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(111, 72, 41));
        panelRound2.setPreferredSize(new java.awt.Dimension(503, 578));
        panelRound2.setRoundBottomLeft(60);
        panelRound2.setRoundBottomRight(60);
        panelRound2.setRoundTopLeft(60);
        panelRound2.setRoundTopRight(60);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        regbtn.setForeground(new java.awt.Color(219, 167, 57));
        regbtn.setText("Register");
        regbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regbtnMouseClicked(evt);
            }
        });
        panelRound2.add(regbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Belum punya akun?");
        panelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        logbtn.setBackground(new java.awt.Color(219, 167, 57));
        logbtn.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        logbtn.setForeground(new java.awt.Color(255, 255, 255));
        logbtn.setText("Login");
        logbtn.setBorderPainted(false);
        logbtn.setPreferredSize(new java.awt.Dimension(192, 54));
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        panelRound2.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        pword.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        panelRound2.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 417, 54));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        panelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        emailAdd.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        emailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddActionPerformed(evt);
            }
        });
        panelRound2.add(emailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 417, 54));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddActionPerformed

    private void regbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regbtnMouseClicked
        // TODO add your handling code here:
        signUp sign = new signUp();
        sign.setVisible(true);
        sign.pack();
        sign.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_regbtnMouseClicked

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
        // TODO add your handling code here:
        String fullname, email, password, query, passdb = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:Mysql://localhost:3306/cafe";
        SUser = "root";
        SPass = "";
        int notFound = 0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement stat = conn.createStatement();
            if("".equals(emailAdd.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Email is require", "Error", JOptionPane.ERROR_MESSAGE);
            } else if("".equals(pword.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password is require", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                email = emailAdd.getText();
                password = pword.getText();
                
                query = "SELECT * FROM userlog WHERE email= '" + email + "'";
                
                ResultSet rs = stat.executeQuery(query);
                while(rs.next()){
                    passdb = rs.getString("password");
                    notFound = 1;
                    
                    fullname = rs.getString("fullname");
                    email = rs.getString("email");
                    password = rs.getString("password");
//                    alamat = rs.getString("alamat");
//                    Blob gambarBlob = rs.getBlob("foto");
                    
                    Model_Login mod = new Model_Login();
                    mod.setFullname(fullname);
                    mod.setEmail(email);
                    mod.setPassword(password);
//                    mod.setAlamat(alamat);
//                    mod.setGambar(gambarBlob);
                    
                    home Home = new home();
                    Home.setVisible(true);
                    Home.revalidate();
                }
                
                if(notFound == 1 && password.equals(passdb)){
                    home HomeFrame = new home();
                    HomeFrame.setVisible(true);
                    HomeFrame.pack();
                    HomeFrame.setLocationRelativeTo(null);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(new JFrame(), "Incorrect email or password", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                pword.setText("");
            }
        }catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_logbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logbtn;
    private PanelRound.PanelRound panelRound2;
    private javax.swing.JPasswordField pword;
    private javax.swing.JLabel regbtn;
    // End of variables declaration//GEN-END:variables
}
