/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package karyawan;

import connection.newConnection;

import Supplier.Supplier;
import laporan.Laporan;
import home.home;
import menu.menu;
//import laporan.Laporan;
import inventaris.inventaris;
import karyawan.absenKaryawan;
import login.logout;
import pelanggan.pelanggan;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER HP
 */
public class inputDataKaryawan extends javax.swing.JFrame {

    public Connection conn = new newConnection().connect();
    private DefaultTableModel tabmode;
    
    /**
     * Creates new form Data
     */
    public inputDataKaryawan() {
        initComponents();
        datatable();
        autoNumberID();
    }
    
    protected void aktif(){
        iname.setEnabled(true);
        itelp.setEnabled(true);
        imail.setEnabled(true);
        itelahir.setEnabled(true);
        italahir.setEnabled(true);
        ialamat.setEnabled(true);
        iname.requestFocus();
    }
    
    private void kosong(){
        iname.setText("");
        itelp.setText("");
        imail.setText("");
        itelahir.setText("");
        italahir.setText("");
        laki.setSelected(true);
        ialamat.setText("");
    }
    
    private void datatable(){
        Object[] Baris = {"ID Karyawan","Nama", "No. Telp", "Email", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelkar.setModel(tabmode);
        String sql = "select * from karyawan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("id_karyawan");
                String a = rs.getString("fullname");
                String b = rs.getString("notelp");
                String c = rs.getString("email");
                String d = rs.getString("tempat_lahir");
                String e = rs.getString("tanggal_lahir");
                String f = rs.getString("jenis_kelamin");
                String g = rs.getString("alamat");
                
                Object[] data = {id,a,b,c,d,e,f,g};
                tabmode.addRow(data);
            }
        } catch(Exception e) {
            System.err.println("DB Error!" + e.getMessage());
        }
    }
    
        private void autoNumberID(){
        String noID = "ID000";
        int i = 0;
        try{
            String sql = "SELECT id_karyawan FROM karyawan";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet rs = stat.executeQuery();
            while(rs.next()){
                noID = rs.getString("id_karyawan");
            }
            noID = noID.substring(2);
            i = Integer.parseInt(noID) + 1;
            noID = "00" + i;
            noID = "ID" + noID.substring(noID.length()-3);
            id.setText(noID);
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Penomoran otomatis gagal! " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dateChooser = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        userdd = new javax.swing.JPanel();
        userbar2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelRound1 = new PanelRound.PanelRound();
        panelRound2 = new PanelRound.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        italahir = new javax.swing.JTextField();
        nama4 = new javax.swing.JLabel();
        iname = new javax.swing.JTextField();
        itelp = new javax.swing.JTextField();
        nama5 = new javax.swing.JLabel();
        nama6 = new javax.swing.JLabel();
        nama7 = new javax.swing.JLabel();
        simpanbtn = new javax.swing.JButton();
        imail = new javax.swing.JTextField();
        datelahirbtn = new javax.swing.JButton();
        nama8 = new javax.swing.JLabel();
        itelahir = new javax.swing.JTextField();
        perem = new javax.swing.JRadioButton();
        nama9 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ialamat = new javax.swing.JTextArea();
        nama10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelkar = new jtable_custom.JTable_Custom();
        id = new javax.swing.JTextField();
        nama11 = new javax.swing.JLabel();
        homebar = new javax.swing.JLabel();
        stokbar = new javax.swing.JLabel();
        orderbar = new javax.swing.JLabel();
        mejabar = new javax.swing.JLabel();
        laporanbar = new javax.swing.JLabel();
        supplierbar = new javax.swing.JLabel();
        karyawanbar = new javax.swing.JLabel();
        userbar = new javax.swing.JLabel();

        dateChooser.setForeground(new java.awt.Color(111, 72, 41));
        dateChooser.setDateFormat("yyyy-MM-dd");
        dateChooser.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dateChooser.setTextRefernce(italahir);
        dateChooser.getAccessibleContext().setAccessibleParent(italahir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1194, 834));
        jPanel1.setPreferredSize(new java.awt.Dimension(1194, 834));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userdd.setBackground(new java.awt.Color(255, 255, 255));
        userdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userbar2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        userbar2.setText("Logout");
        userbar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbar2MouseClicked(evt);
            }
        });
        userdd.add(userbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(userdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, -1, 10));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1200, 20));

        panelRound1.setBackground(new java.awt.Color(206, 194, 182));
        panelRound1.setPreferredSize(new java.awt.Dimension(1140, 700));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(111, 72, 41));
        panelRound2.setPreferredSize(new java.awt.Dimension(1140, 38));
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Input Data Karyawan");
        panelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        panelRound2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 30, 40));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        italahir.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        italahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italahirActionPerformed(evt);
            }
        });
        panelRound1.add(italahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 250, 30));

        nama4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama4.setForeground(new java.awt.Color(255, 255, 255));
        nama4.setText("Nama");
        panelRound1.add(nama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        iname.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        iname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inameActionPerformed(evt);
            }
        });
        panelRound1.add(iname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, 30));

        itelp.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        itelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itelpActionPerformed(evt);
            }
        });
        panelRound1.add(itelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 300, 30));

        nama5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama5.setForeground(new java.awt.Color(255, 255, 255));
        nama5.setText("No. Telp");
        panelRound1.add(nama5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        nama6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama6.setForeground(new java.awt.Color(255, 255, 255));
        nama6.setText("Email");
        panelRound1.add(nama6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        nama7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama7.setForeground(new java.awt.Color(255, 255, 255));
        nama7.setText("Alamat");
        panelRound1.add(nama7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, -1, -1));

        simpanbtn.setBackground(new java.awt.Color(219, 167, 57));
        simpanbtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        simpanbtn.setForeground(new java.awt.Color(255, 255, 255));
        simpanbtn.setText("Simpan");
        simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbtnActionPerformed(evt);
            }
        });
        panelRound1.add(simpanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 300, 30));

        imail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        imail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imailActionPerformed(evt);
            }
        });
        panelRound1.add(imail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 300, 30));

        datelahirbtn.setText("...");
        datelahirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datelahirbtnActionPerformed(evt);
            }
        });
        panelRound1.add(datelahirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 40, 30));

        nama8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama8.setForeground(new java.awt.Color(255, 255, 255));
        nama8.setText("Tempat Lahir");
        panelRound1.add(nama8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        itelahir.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        itelahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itelahirActionPerformed(evt);
            }
        });
        panelRound1.add(itelahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 300, 30));

        buttonGroup1.add(perem);
        perem.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        perem.setForeground(new java.awt.Color(255, 255, 255));
        perem.setText("Perempuan");
        panelRound1.add(perem, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, 30));

        nama9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama9.setForeground(new java.awt.Color(255, 255, 255));
        nama9.setText("Tanggal Lahir");
        panelRound1.add(nama9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        buttonGroup1.add(laki);
        laki.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        laki.setForeground(new java.awt.Color(255, 255, 255));
        laki.setText("Laki-laki");
        panelRound1.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, 30));

        ialamat.setColumns(20);
        ialamat.setRows(5);
        jScrollPane1.setViewportView(ialamat);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 300, 100));

        nama10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama10.setForeground(new java.awt.Color(255, 255, 255));
        nama10.setText("Jenis Kelamin");
        panelRound1.add(nama10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        tabelkar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Karyawan", "Nama", "No. Telp", "Email", "Tempat Lahir", "Tempat Lahir", "Jenis Kelamin", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tabelkar);

        panelRound1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 1060, 360));

        id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        panelRound1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 300, 30));

        nama11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nama11.setForeground(new java.awt.Color(255, 255, 255));
        nama11.setText("ID Karyawan");
        panelRound1.add(nama11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 720));

        homebar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        homebar.setText("Home");
        homebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebarMouseExited(evt);
            }
        });
        jPanel1.add(homebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, -1));

        stokbar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        stokbar.setText("Stok");
        stokbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stokbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stokbarMouseExited(evt);
            }
        });
        jPanel1.add(stokbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, -1));

        orderbar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        orderbar.setText("Order");
        orderbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderbarMouseExited(evt);
            }
        });
        jPanel1.add(orderbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, -1));

        mejabar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        mejabar.setText("Pelanggan");
        mejabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mejabarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mejabarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mejabarMouseExited(evt);
            }
        });
        jPanel1.add(mejabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 100, -1));

        laporanbar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        laporanbar.setText("Laporan");
        laporanbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanbarMouseExited(evt);
            }
        });
        jPanel1.add(laporanbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 80, -1));

        supplierbar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        supplierbar.setText("Supplier");
        supplierbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierbarMouseExited(evt);
            }
        });
        jPanel1.add(supplierbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 80, -1));

        karyawanbar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        karyawanbar.setText("Karyawan");
        karyawanbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                karyawanbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                karyawanbarMouseExited(evt);
            }
        });
        jPanel1.add(karyawanbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 100, -1));

        userbar.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        userbar.setText("Owner");
        userbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userbarMouseExited(evt);
            }
        });
        jPanel1.add(userbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userbar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbar2MouseClicked
        // TODO add your handling code here:
        logout Logout = new logout();
        Logout.setVisible(true);
        Logout.pack();
        Logout.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_userbar2MouseClicked

    private void italahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_italahirActionPerformed

    private void inameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inameActionPerformed

    private void itelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itelpActionPerformed

    private void simpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbtnActionPerformed
        String sql = "insert into karyawan values (?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, id.getText());
            stat.setString(2, iname.getText());
            stat.setString(3, itelp.getText());
            stat.setString(4, imail.getText());
            stat.setString(5, itelahir.getText());
            stat.setString(6, italahir.getText());
            
            String jk = "";
            if(laki.isSelected()) jk = "Laki-laki";
            else jk = "Perempuan";
            stat.setString(7, jk);
            
//            if(laki.isSelected()) jk = "Laki-laki";
            
            stat.setString(8, ialamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data saved successfully!");
            autoNumberID();
            kosong();
            iname.requestFocus();
            datatable();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Data failed to save! " + e);
        }
    }//GEN-LAST:event_simpanbtnActionPerformed

    private void imailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imailActionPerformed

    private void datelahirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datelahirbtnActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_datelahirbtnActionPerformed

    private void homebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebarMouseClicked
        // TODO add your handling code here:
        home Home = new home();
        Home.setVisible(true);
        Home.pack();
        Home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homebarMouseClicked

    private void homebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebarMouseEntered
        homebar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_homebarMouseEntered

    private void homebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebarMouseExited
        homebar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_homebarMouseExited

    private void stokbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokbarMouseClicked
        inventaris stok = new inventaris();
        stok.setVisible(true);
        stok.pack();
        stok.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_stokbarMouseClicked

    private void stokbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokbarMouseEntered
        stokbar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_stokbarMouseEntered

    private void stokbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokbarMouseExited
        stokbar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_stokbarMouseExited

    private void orderbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderbarMouseClicked
        menu or = new menu();
        or.setVisible(true);
        or.pack();
        or.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_orderbarMouseClicked

    private void orderbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderbarMouseEntered
        orderbar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_orderbarMouseEntered

    private void orderbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderbarMouseExited
        orderbar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_orderbarMouseExited

    private void mejabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mejabarMouseClicked
        pelanggan Meja = new pelanggan();
        Meja.setVisible(true);
        Meja.pack();
        Meja.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mejabarMouseClicked

    private void mejabarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mejabarMouseEntered
        mejabar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_mejabarMouseEntered

    private void mejabarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mejabarMouseExited
        mejabar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_mejabarMouseExited

    private void laporanbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanbarMouseEntered
        laporanbar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_laporanbarMouseEntered

    private void laporanbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanbarMouseExited
        laporanbar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_laporanbarMouseExited

    private void supplierbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierbarMouseClicked
        Supplier sup = new Supplier();
        sup.setVisible(true);
        sup.pack();
        sup.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_supplierbarMouseClicked

    private void supplierbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierbarMouseEntered
        supplierbar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_supplierbarMouseEntered

    private void supplierbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierbarMouseExited
        supplierbar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_supplierbarMouseExited

    private void karyawanbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanbarMouseClicked
        absenKaryawan Kar = new absenKaryawan();
        Kar.setVisible(true);
        Kar.pack();
        Kar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_karyawanbarMouseClicked

    private void karyawanbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanbarMouseEntered
        karyawanbar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_karyawanbarMouseEntered

    private void karyawanbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanbarMouseExited
        karyawanbar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_karyawanbarMouseExited

    private void userbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbarMouseClicked
        userdd.setSize(76, 40);
    }//GEN-LAST:event_userbarMouseClicked

    private void userbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbarMouseEntered
        userbar.setForeground(new Color(206,194,182));
    }//GEN-LAST:event_userbarMouseEntered

    private void userbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbarMouseExited
        userbar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_userbarMouseExited

    private void itelahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itelahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itelahirActionPerformed

    private void laporanbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanbarMouseClicked
        Laporan lap = new Laporan();
        lap.setVisible(true);
        lap.pack();
        lap.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_laporanbarMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JButton datelahirbtn;
    private javax.swing.JLabel homebar;
    private javax.swing.JTextArea ialamat;
    private javax.swing.JTextField id;
    private javax.swing.JTextField imail;
    private javax.swing.JTextField iname;
    private javax.swing.JTextField italahir;
    private javax.swing.JTextField itelahir;
    private javax.swing.JTextField itelp;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel karyawanbar;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel laporanbar;
    private javax.swing.JLabel mejabar;
    private javax.swing.JLabel nama10;
    private javax.swing.JLabel nama11;
    private javax.swing.JLabel nama4;
    private javax.swing.JLabel nama5;
    private javax.swing.JLabel nama6;
    private javax.swing.JLabel nama7;
    private javax.swing.JLabel nama8;
    private javax.swing.JLabel nama9;
    private javax.swing.JLabel orderbar;
    private PanelRound.PanelRound panelRound1;
    private PanelRound.PanelRound panelRound2;
    private javax.swing.JRadioButton perem;
    private javax.swing.JButton simpanbtn;
    private javax.swing.JLabel stokbar;
    private javax.swing.JLabel supplierbar;
    private jtable_custom.JTable_Custom tabelkar;
    private javax.swing.JLabel userbar;
    private javax.swing.JLabel userbar2;
    private javax.swing.JPanel userdd;
    // End of variables declaration//GEN-END:variables
}
